- name: Remove Cloud-Init Connection
  nmcli:
    conn_name: "System eth0"
    ifname: "{{ vm.network[0].ifname }}"
    type: ethernet
    state: absent

- name: Remove Cloud-Init NetworkManager config
  ini_file:
    section: main
    path: /etc/NetworkManager/conf.d/99-cloud-init.conf
    option: dns
    value: none # default
    state: absent # present
