---
# tasks file for rhv_rhel7_qcow2_provision
- include_tasks: rhv/login.yml

- name: Generate new VM
  delegate_to: localhost
  # delegate_facts: yes
  block:
    - include_tasks: disk/upload.yml

    - include_tasks: machine/create.yml

    - include_tasks: disk/resize.yml

    - include_tasks: machine/start.yml

  rescue:
    - include_tasks: machine/delete.yml

  always:
    - include_tasks: rhv/logout.yml

# - include_tasks: network.yml
