---
# tasks file for rhv_rhel7_qcow2_provision
- include_tasks: rhv/login.yml

- name: Generate new VM
  delegate_to: localhost
  block:
    - include_tasks: disk/upload.yml

    - include_tasks: machine/create.yml

    - name: Pause for VM Creation
      pause:
        seconds: 10

    - include_tasks: disk/resize.yml

    - name: Pause for Disk Resize
      pause:
        seconds: 10

    - include_tasks: machine/start.yml

    - name: Wait for VM Start
      pause:
        seconds: 10

  rescue:
    - include_tasks: machine/delete.yml

  always:
    - include_tasks: rhv/logout.yml

#- include_tasks: network.yml
